### ISSUE TITLE
_putnlscode as a configuration

### ISSUE THREAD

**Issue by klikin** [nlac/nlsclientscript#10]
Is "_putnlscode" function injecting a script just to "fixDuplicateResources" (as the name of the registerScript parameter says) ?

If yes, is it totally necessary ? Since this javascript injected *needs* jQuery, NLS obeys me to add jQuery in my HEAD section to work, and Google PageSpeed does not like that at all, since jQuery load is a "blocker" for UX.

So, AFAIK the "nlscode" is to review and check possible duplicate resources written within the page as  < script >, right ?

If I know I'm using always the Yii RegisterScript, I could get rid of this function, therefore I'd not need NLS to inject this in my HEAD section.

Therefore ... can you add a configuration setting to be able to turn off/on the _putnlscode call ?

Thank you !!!

**Comment by nlac** [comment]
ok, just for curiosity, what feature do you use of nlsclientscript in your app?

**Comment by klikin** [comment]
JS and CSS merge

**Comment by nlac** [comment]
ok.. i'll inspect if putting the js code to the end of the body would have some negative impact (at least i can put an option to decide where to put). I'm not sure i want to add option to entirely turn it off - it's the core functionality of the extension.
It will likely be included into the next release, with some other refactors.

**Comment by klikin** [comment]
Since it's a code that needs jQuery, I would add, as you suggested, an option to decide where to put, and a native javascript code to load that code after jQuery is loaded ... 

or maybe just ask yourself :  do I really need jQuery for that code ?  you shouldn't :-P

**Comment by nlac** [comment]
you can control the nls-snippet insertion mode by setting the nlsScriptPosition param in the app config file to false (no snippet/jQuery.js will be inserted) or CClientScript::POS_XXX
