### ISSUE TITLE
When apache has CSS or JS files cached NLS fails to change the content in the created files

### ISSUE THREAD

**Issue by jplozgom** [nlac/nlsclientscript#11]
Hi. First thanks for such a great extension, I've been using it for the last two years.

I've been improving my server cache options and I also installed Pagespeed mod on it. After enabling these options in the server I found that NLS extension didn't worked when I made changes on the stylesheets (or at least these changes where not reflected on the assets/nls files, it didn't matter if I added extra CSS files, more CSS rules, or set the appVersion to a different number. The App Version number did work when I needed pagespeed mod to create new files ).

After testing I found that NLS was receiving the cached version of every CSS file instead of the most recent which had a minor change. After trying different things I realized that maybe adding the appVersion at the end of the CSS filenames could work to avoid the cached version, so I tried this by adding a number version manually to the script filename when it was registered and it worked. 

    registerCssFile(Yii::app()->getBaseUrl(true) . '/stylesheets/sections/categories.css?2.2');

Therefore I think that adding the appVersion when files are merged (_mergeCss) could solve this issue. 

    if ($this->appVersion){
	  $url .= (parse_url($url, PHP_URL_QUERY) ? '&' : '?').$this->appVersion;
    }

Please give me your opinion on this .

thanks

**Comment by nlac** [comment]
Thanks for your feedback. It's indeed important to append the version (if set) when referring to the file URLs, on both client and server side.. i'll include it in the next version.

For first thougth, i think NLSClientScript may optionally override registerCssFile and registerScriptFile, to append the version param to the local URLs, that could automatize the ```categories.css?2.2``` part. Beside, the version should be appended to the url every place when ```downloader->toAbsUrl``` is called.

**Comment by jplozgom** [comment]
Ok, i's great if you can add this on the next release or version. I never thought of NLSclientscript overriding the register CSS and JS, but it could be a good approach. Actually my idea was more related to the downloader->toAbsUrl , something like this

    if ($this->appVersion){
        $url .= (parse_url($url, PHP_URL_QUERY) ? '&' : '?').$this->appVersion;
    }

    $absUrl = $this->downloader->toAbsUrl($url);


I'll be looking foward for this new feature and I'll test it on my web app (http://bogota.somosdogfriendly.com you can observe here the use of NLSClientscript and how pagespeed changed the script file and optimise these even more) when it's available. Please let me know if you need more feedback on this.

thanks

**Comment by nlac** [comment]
pls check if the issue has been solved with the latest tag.

**Comment by jplozgom** [comment]
Great, I'll look at it tomorrow and I'll let you know.

thanks
