### ISSUE TITLE
unexpected '@

### ISSUE THREAD

**Issue by 3dgroup** [nlac/nlsclientscript#13]
Parse error: syntax error, unexpected '@' in \NLSUtils.php on line 9.

PHP is 5.4.27

**Comment by nlac** [comment]
Sorry, i still haven't got the smallest clue why you experience that. PHP 5.4 is perfectly compatible with NLSClientScript, noone complained about such parse error expect you..

Can you compare the content of that file with a just-downloaded instance (perhaps an accidental typo damaged it when you debugged etc)?

**Comment by nlac** [comment]
Have you checked it? It's easy i guess?

**Comment by 3dgroup** [comment]
Sorry for late reply. I haven't changed anything with debugging. The only debug I had to do on the latest version was to correct this issue. It may just be a php config issue on my local XAMP. I will test on another set up tomorrow.
