### ISSUE TITLE
Error compressing twitter widgets minified script

### ISSUE THREAD

**Issue by sucotronic** [nlac/nlsclientscript#15]
We use around 30 different js files with libraries and other stuff, and the nlsclientscript works well with them. But when I try to add twitter widgets library, the browser complains about missing parenthesis and other stuff. 

You can test it adding the twitter widgets library to any example and enable compress:

    https://platform.twitter.com/widgets.js

**Comment by nlac** [comment]
Hi,
i don't really want to:) On the demo page http://nlacsoft.net/nlsclientscript/merging-js, there's a section: 
> "The minification is done by the JShrink library. That's a 3rd party, so in case of js minification issues please turn to its developers."

I really mean it ;)

Alternatively you may set a regexp in the config file:
``` 'mergeJsExcludePattern' => '/twitter\\.com/i' ```

so NLSClientScript won't merge and compress it but will link it separately instead.

Let me know if the workaround fixed the issue.

**Comment by nlac** [comment]
Has the workaround fixed the issue? Another chance is to link the uncompressed version (if any) of the file, the minification may work for that.
