### ISSUE TITLE
Exclude/Include patterns

### ISSUE THREAD

**Issue by Tpona** [nlac/nlsclientscript#16]
Hi!
How can i specify multiple of patterns?

**Comment by nlac** [comment]
Hi, 
those properties are regular expressions that should match (partially) to the url of the files. So eg. do not process scripts from some domains:
```'excludePattern' => '/jquery\.com|nlacsoft\.net|github\.com/'```

There are dozens of tutorials/examples out there about regexp, eg. http://www.regexr.com, https://regex101.com
