### ISSUE TITLE
How load nlsclientscript asynchronus?

### ISSUE THREAD

**Issue by PendalF89** [nlac/nlsclientscript#17]
Hello!
Your extension is awesome! But i want load nlsclientscript asynchronus. How i can do this?

**Comment by nlac** [comment]
Thank you. Check out the parameter nlsScriptPosition in NLSClientScript.php. If you set it to false, the snippet won't be inserted, and you may attempt to load the snipped async "by hand", but i cannot guarantee it will work and to be honest i can't see why it is needed.

**Comment by PendalF89** [comment]
Sorry for my english, but i was mean output js script

**Comment by nlac** [comment]
I'm lost:). Could you explain from the beginning, what do you want to achieve and why? Some example  case would be useful.

**Comment by PendalF89** [comment]
![2015-06-17 19-31-41](https://cloud.githubusercontent.com/assets/5278851/8212986/aeeafd54-1527-11e5-918a-5fd36949c250.png)

**Comment by nlac** [comment]
Ah i get it.. Currently there isn't an option to do this but it's easy to add it as a new feature (a new property "mergedScriptOptions"). I'll include it in the upcoming version.

**Comment by PendalF89** [comment]
What method in NLSClientScript returns "finish" compressed script? Were i can edit this?

**Comment by nlac** [comment]
NLSClientScript.php, line 330: ```$finalScriptFiles[$url] = $url;``` 

the second $url should be changed to a map of html options.

**Comment by PendalF89** [comment]
Thanks a lot man! :+1:
